
title: Tora Tech Github
logo: "https://www.tora.tech/img/DetailedColour-800x800.png"
description: >
  Code . Repair . Support 
  <br><br>
  We are a small software development and business technical support company based in East Sussex, UK
  <br><br>
  <a href="https://uk.linkedin.com/company/toratechnology">View Our LinkedIn Profile</a> 
  
remote_theme: orderedlist/minimal
google_analytics: UA-000000-0
